# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-03-07 04:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msn', models.CharField(max_length=32, unique=True)),
                ('harness_length', models.IntegerField()),
                ('gross_weight', models.IntegerField()),
                ('fuel_capacity_left_wing', models.IntegerField()),
                ('fuel_capacity_right_wing', models.IntegerField()),
                ('maximum_altitude', models.IntegerField()),
                ('make_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AircraftModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Headline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brief', models.CharField(max_length=100)),
                ('story', models.TextField()),
                ('image', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='headline',
            name='tags',
            field=models.ManyToManyField(to='cms.Tags'),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.AircraftModel'),
        ),
    ]
