# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-03-07 05:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('country', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_no', models.CharField(max_length=64, unique=True)),
                ('diversion_reason', models.CharField(max_length=100)),
                ('atmospheric_pressure', models.IntegerField()),
                ('room_temp', models.IntegerField()),
                ('max_altitude_reached', models.IntegerField()),
                ('departure_time', models.TimeField()),
                ('planned_arrival_time', models.TimeField()),
                ('actual_arrival_time', models.TimeField()),
                ('departure_date', models.DateField()),
                ('planned_arrival_date', models.DateField()),
                ('actual_arrival_date', models.DateField()),
                ('abberation', models.BooleanField()),
                ('emergency', models.BooleanField()),
                ('abberation_reason', models.TextField()),
                ('emergency_reason', models.TextField()),
                ('luggage_weight', models.IntegerField()),
                ('passenger_strength', models.IntegerField()),
                ('cabin_crew_strength', models.IntegerField()),
                ('actual_destination_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='act_dest_airport', to='cms.Airport')),
            ],
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='fuel_capacity_left_wing',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='fuel_capacity_right_wing',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='gross_weight',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='maximum_altitude',
        ),
        migrations.AddField(
            model_name='aircraftmodel',
            name='fuel_capacity_left_wing',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aircraftmodel',
            name='fuel_capacity_right_wing',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aircraftmodel',
            name='gross_weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aircraftmodel',
            name='maximum_altitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='headline',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='headline',
            name='headline',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='headline',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='aircraftmodel',
            name='name',
            field=models.CharField(default='null', max_length=32),
        ),
        migrations.AlterField(
            model_name='headline',
            name='brief',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='headline',
            name='image',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='headline',
            name='story',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='headline',
            name='tags',
            field=models.ManyToManyField(null=True, to='cms.Tags'),
        ),
        migrations.AddField(
            model_name='flight',
            name='aircraft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Aircraft'),
        ),
        migrations.AddField(
            model_name='flight',
            name='departure_airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Airport'),
        ),
        migrations.AddField(
            model_name='flight',
            name='planned_destination_airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plnd_dest_airport', to='cms.Airport'),
        ),
    ]
