# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-03-07 06:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20190307_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headline',
            name='tags',
        ),
    ]
